"""
OpenCrew Setup Wizard
=====================
One-command setup: python setup.py

Asks user for config, generates .env, builds everything, starts services.
"""

import os
import sys
import shutil
from pathlib import Path

ROOT = Path(__file__).parent
ENV_FILE = ROOT / ".env"
ENV_EXAMPLE = ROOT / ".env.example"

MODELS = {
    "1": {
        "name": "MiMo v2.5 Pro (recommended, cheap)",
        "provider": "openai",
        "model": "mimo-v2.5-pro",
        "base_url": "https://token-plan-sgp.xiaomimimo.com/v1",
        "needs_key": True,
        "key_name": "MIMO_API_KEY",
        "cost": "~$0.001/1K tokens",
    },
    "2": {
        "name": "Ollama + Qwen2.5 7B (free, local, needs GPU 8GB+)",
        "provider": "ollama",
        "model": "qwen2.5:7b",
        "base_url": "http://localhost:11434",
        "needs_key": False,
        "key_name": None,
        "cost": "$0 (local)",
    },
    "3": {
        "name": "Gemini 2.5 Flash (free tier, rate limited)",
        "provider": "gemini",
        "model": "gemini-2.5-flash",
        "base_url": None,
        "needs_key": True,
        "key_name": "GEMINI_API_KEY",
        "cost": "$0 (free tier)",
    },
    "4": {
        "name": "Qwen 2.5 (free from Alibaba)",
        "provider": "openai",
        "model": "qwen2.5-72b-instruct",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "needs_key": True,
        "key_name": "QWEN_API_KEY",
        "cost": "$0 (free tier)",
    },
    "5": {
        "name": "GPT-4o (expensive, high quality)",
        "provider": "openai",
        "model": "gpt-4o",
        "base_url": "https://api.openai.com/v1",
        "needs_key": True,
        "key_name": "OPENAI_API_KEY",
        "cost": "~$0.005/1K tokens",
    },
}


def print_banner():
    print("""
╔══════════════════════════════════════════════════╗
║           OpenCrew Setup Wizard                  ║
║   11 AI agents that build software for you       ║
╚══════════════════════════════════════════════════╝
""")


def choose_model():
    print("Choose your LLM model:\n")
    for key, model in MODELS.items():
        print(f"  [{key}] {model['name']}")
        print(f"      Cost: {model['cost']}")
        print()

    while True:
        choice = input("Enter choice [1-5]: ").strip()
        if choice in MODELS:
            return MODELS[choice]
        print("Invalid choice. Try again.")


def get_api_key(model_config):
    if not model_config["needs_key"]:
        return None

    key_name = model_config["key_name"]
    key = input(f"\nEnter your {key_name}: ").strip()
    if not key:
        print(f"Warning: No {key_name} provided. You'll need to add it to .env later.")
    return key


def get_github_token():
    token = input("\nGitHub token (optional, press Enter to skip): ").strip()
    return token if token else None


def generate_env(model_config, api_key, github_token):
    env_content = f"""# ===== MODEL CONFIG =====
# Generated by OpenCrew Setup Wizard

DEFAULT_LLM_PROVIDER={model_config['provider']}
DEFAULT_LLM_MODEL={model_config['model']}
"""

    if model_config["base_url"]:
        env_content += f"DEFAULT_LLM_BASE_URL={model_config['base_url']}\n"

    if api_key:
        env_content += f"DEFAULT_LLM_API_KEY={api_key}\n"
    else:
        env_content += f"# DEFAULT_LLM_API_KEY=your-key-here\n"

    env_content += """
# Max tokens per request (0 = unlimited)
MAX_TOKENS=0

# ===== GITHUB =====
"""
    if github_token:
        env_content += f"GITHUB_TOKEN={github_token}\n"
    else:
        env_content += "# GITHUB_TOKEN=your-github-token\n"

    env_content += """
# ===== REDIS =====
REDIS_URL=redis://localhost:6379

# ===== AGENT CONFIG =====
AGENT_LOOP_MAX_ITERATIONS=10
LLM_TEMPERATURE=0.2
LLM_TIMEOUT=120
LLM_MAX_RETRIES=3
"""

    ENV_FILE.write_text(env_content, encoding="utf-8")
    print(f"\n.env created at {ENV_FILE}")


def build_output():
    print("\nBuilding all code files...")
    print("This will call MiMo API to generate 116 files.")
    print("Estimated time: 1-2 hours")
    print()

    confirm = input("Start build now? [y/N]: ").strip().lower()
    if confirm == "y":
        os.system(f"{sys.executable} build.py")
    else:
        print("Skip build. Run 'python build.py' later.")


def main():
    print_banner()

    if ENV_FILE.exists():
        overwrite = input(".env already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Keeping existing .env")
            return

    model_config = choose_model()
    api_key = get_api_key(model_config)
    github_token = get_github_token()

    generate_env(model_config, api_key, github_token)

    print("\n" + "=" * 50)
    print("Setup complete!")
    print("=" * 50)
    print(f"\nModel: {model_config['name']}")
    print(f"Cost: {model_config['cost']}")
    print(f"\nNext steps:")
    print(f"  1. python build.py          # Generate all code")
    print(f"  2. cd output && docker-compose up  # Start all services")
    print(f"  3. Open http://localhost:3000       # Web UI")

    build_output()


if __name__ == "__main__":
    main()
